#!/bin/bash
# -*- c-basic-offset: 4; indent-tabs-mode: nil -*-

## Copyright 2018-19, Lancaster University
## All rights reserved.
## 
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions are
## met:
## 
##  * Redistributions of source code must retain the above copyright
##    notice, this list of conditions and the following disclaimer.
## 
##  * Redistributions in binary form must reproduce the above copyright
##    notice, this list of conditions and the following disclaimer in the
##    documentation and/or other materials provided with the
##    distribution.
## 
##  * Neither the name of the copyright holder nor the names of
##    its contributors may be used to endorse or promote products derived
##    from this software without specific prior written permission.
## 
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
## "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
## LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
## A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
## OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
## SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
## LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
## DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
## THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
## (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
## OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##
##
## Author: Steven Simpson <https://github.com/simpsonst>

SHARE_DIR="$(readlink -f "${0%/*}")"

source "${SHARE_DIR}/defaults.sh"
source "${SHARE_DIR}/common.sh"

while true ; do
    ## Wait for the suppression file to be deleted; while it is
    ## present we don't start up a new streamer.  This command also
    ## fails if the file does not exist, so there's no race condition.
    printf 'Awaiting removal of %s...\n' "$SUPPRESS_FILE" > /dev/stderr
    inotifywait -qq -e delete "$SUPPRESS_FILE" 2> /dev/null || true

    ## Create the file again so we can detect the next request.
    touch "$SUPPRESS_FILE"

    ## Take many frames at a given rate, and store each as a separate
    ## file in the raw directory.  The rotator process will rotate
    ## them and drop in the snap directory.
    printf 'New cycle\n' > /dev/stderr
    streamer -q "${STREAMER[@]}" -f jpeg -o "$RAW_DIR/snap000.jpeg"
done
